spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop

#graphite:
#  host: ${GRAPHITE_HOST}
#  apiKey: ${HOSTEDGRAPHITE_APIKEY}

logging:
  level:
    org.hibernate: ERROR
    org.springframework.web: INFO